name: Empanadas
rules:
  - image: Nro00-Iluminado.png
    when:
      black: 0
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro01-Iluminado.png
    when:
      black: 1
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro02-Iluminado.png
    when:
      black: 2
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro03-Iluminado.png
    when:
      black: 3
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro04-Iluminado.png
    when:
      black: 4
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro05-Iluminado.png
    when:
      black: 5
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro06-Iluminado.png
    when:
      black: 6
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro07-Iluminado.png
    when:
      black: 7
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro08-Iluminado.png
    when:
      black: 8
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro09-Iluminado.png
    when:
      black: 9
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro10-Iluminado.png
    when:
      black: 10
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro11-Iluminado.png
    when:
      black: 11
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro12-Iluminado.png
    when:
      black: 12
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro13-Iluminado.png
    when:
      black: 13
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro14-Iluminado.png
    when:
      black: 14
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro15-Iluminado.png
    when:
      black: 15
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro16-Iluminado.png
    when:
      black: 16
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro17-Iluminado.png
    when:
      black: 17
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro18-Iluminado.png
    when:
      black: 18
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro19-Iluminado.png
    when:
      black: 19
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro20-Iluminado.png
    when:
      black: 20
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro21-Iluminado.png
    when:
      black: 21
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro22-Iluminado.png
    when:
      black: 22
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro23-Iluminado.png
    when:
      black: 23
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro24-Iluminado.png
    when:
      black: 24
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro25-Iluminado.png
    when:
      black: 25
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro26-Iluminado.png
    when:
      black: 26
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro27-Iluminado.png
    when:
      black: 27
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro28-Iluminado.png
    when:
      black: 28
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro29-Iluminado.png
    when:
      black: 29
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro30-Iluminado.png
    when:
      black: 30
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro31-Iluminado.png
    when:
      black: 31
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro32-Iluminado.png
    when:
      black: 32
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro33-Iluminado.png
    when:
      black: 33
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro34-Iluminado.png
    when:
      black: 34
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro35-Iluminado.png
    when:
      black: 35
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro36-Iluminado.png
    when:
      black: 36
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro37-Iluminado.png
    when:
      black: 37
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro38-Iluminado.png
    when:
      black: 38
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro39-Iluminado.png
    when:
      black: 39
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro40-Iluminado.png
    when:
      black: 40
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro41-Iluminado.png
    when:
      black: 41
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro42-Iluminado.png
    when:
      black: 42
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro43-Iluminado.png
    when:
      black: 43
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro44-Iluminado.png
    when:
      black: 44
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro45-Iluminado.png
    when:
      black: 45
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro46-Iluminado.png
    when:
      black: 46
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro47-Iluminado.png
    when:
      black: 47
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro48-Iluminado.png
    when:
      black: 48
      blue: 0
      green: 0
      head: true
      red: 0
  - image: Nro00.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Nro01.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: Nro02.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 0
  - image: Nro03.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 0
  - image: Nro04.png
    when:
      black: 4
      blue: 0
      green: 0
      red: 0
  - image: Nro05.png
    when:
      black: 5
      blue: 0
      green: 0
      red: 0
  - image: Nro06.png
    when:
      black: 6
      blue: 0
      green: 0
      red: 0
  - image: Nro07.png
    when:
      black: 7
      blue: 0
      green: 0
      red: 0
  - image: Nro08.png
    when:
      black: 8
      blue: 0
      green: 0
      red: 0
  - image: Nro09.png
    when:
      black: 9
      blue: 0
      green: 0
      red: 0
  - image: Nro10.png
    when:
      black: 10
      blue: 0
      green: 0
      red: 0
  - image: Nro11.png
    when:
      black: 11
      blue: 0
      green: 0
      red: 0
  - image: Nro12.png
    when:
      black: 12
      blue: 0
      green: 0
      red: 0
  - image: Nro13.png
    when:
      black: 13
      blue: 0
      green: 0
      red: 0
  - image: Nro14.png
    when:
      black: 14
      blue: 0
      green: 0
      red: 0
  - image: Nro15.png
    when:
      black: 15
      blue: 0
      green: 0
      red: 0
  - image: Nro16.png
    when:
      black: 16
      blue: 0
      green: 0
      red: 0
  - image: Nro17.png
    when:
      black: 17
      blue: 0
      green: 0
      red: 0
  - image: Nro18.png
    when:
      black: 18
      blue: 0
      green: 0
      red: 0
  - image: Nro19.png
    when:
      black: 19
      blue: 0
      green: 0
      red: 0
  - image: Nro20.png
    when:
      black: 20
      blue: 0
      green: 0
      red: 0
  - image: Nro21.png
    when:
      black: 21
      blue: 0
      green: 0
      red: 0
  - image: Nro22.png
    when:
      black: 22
      blue: 0
      green: 0
      red: 0
  - image: Nro23.png
    when:
      black: 23
      blue: 0
      green: 0
      red: 0
  - image: Nro24.png
    when:
      black: 24
      blue: 0
      green: 0
      red: 0
  - image: Nro25.png
    when:
      black: 25
      blue: 0
      green: 0
      red: 0
  - image: Nro26.png
    when:
      black: 26
      blue: 0
      green: 0
      red: 0
  - image: Nro27.png
    when:
      black: 27
      blue: 0
      green: 0
      red: 0
  - image: Nro28.png
    when:
      black: 28
      blue: 0
      green: 0
      red: 0
  - image: Nro29.png
    when:
      black: 29
      blue: 0
      green: 0
      red: 0
  - image: Nro30.png
    when:
      black: 30
      blue: 0
      green: 0
      red: 0
  - image: Nro31.png
    when:
      black: 31
      blue: 0
      green: 0
      red: 0
  - image: Nro32.png
    when:
      black: 32
      blue: 0
      green: 0
      red: 0
  - image: Nro33.png
    when:
      black: 33
      blue: 0
      green: 0
      red: 0
  - image: Nro34.png
    when:
      black: 34
      blue: 0
      green: 0
      red: 0
  - image: Nro35.png
    when:
      black: 35
      blue: 0
      green: 0
      red: 0
  - image: Nro36.png
    when:
      black: 36
      blue: 0
      green: 0
      red: 0
  - image: Nro37.png
    when:
      black: 37
      blue: 0
      green: 0
      red: 0
  - image: Nro38.png
    when:
      black: 38
      blue: 0
      green: 0
      red: 0
  - image: Nro39.png
    when:
      black: 39
      blue: 0
      green: 0
      red: 0
  - image: Nro40.png
    when:
      black: 40
      blue: 0
      green: 0
      red: 0
  - image: Nro41.png
    when:
      black: 41
      blue: 0
      green: 0
      red: 0
  - image: Nro42.png
    when:
      black: 42
      blue: 0
      green: 0
      red: 0
  - image: Nro43.png
    when:
      black: 43
      blue: 0
      green: 0
      red: 0
  - image: Nro44.png
    when:
      black: 44
      blue: 0
      green: 0
      red: 0
  - image: Nro45.png
    when:
      black: 45
      blue: 0
      green: 0
      red: 0
  - image: Nro46.png
    when:
      black: 46
      blue: 0
      green: 0
      red: 0
  - image: Nro47.png
    when:
      black: 47
      blue: 0
      green: 0
      red: 0
  - image: Nro48.png
    when:
      black: 48
      blue: 0
      green: 0
      red: 0
  - image: Empanada01.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: Empanada02.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 0
  - image: Empanada03.png
    when:
      black: 0
      blue: 3
      green: 0
      red: 0
  - image: Empanada04.png
    when:
      black: 0
      blue: 4
      green: 0
      red: 0
  - image: Empanada05.png
    when:
      black: 0
      blue: 5
      green: 0
      red: 0
  - image: Empanada06.png
    when:
      black: 0
      blue: 6
      green: 0
      red: 0
  - image: Empanada07.png
    when:
      black: 0
      blue: 7
      green: 0
      red: 0
  - image: Empanada08.png
    when:
      black: 0
      blue: 8
      green: 0
      red: 0
  - image: Empanada09.png
    when:
      black: 0
      blue: 9
      green: 0
      red: 0
  - image: Empanada10.png
    when:
      black: 0
      blue: 10
      green: 0
      red: 0
  - image: Empanada01-Iluminada.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 1
  - image: Empanada02-Iluminada.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 1
  - image: Empanada03-Iluminada.png
    when:
      black: 0
      blue: 3
      green: 0
      red: 1
  - image: Empanada04-Iluminada.png
    when:
      black: 0
      blue: 4
      green: 0
      red: 1
  - image: Empanada05-Iluminada.png
    when:
      black: 0
      blue: 5
      green: 0
      red: 1
  - image: Empanada06-Iluminada.png
    when:
      black: 0
      blue: 6
      green: 0
      red: 1
  - image: Empanada07-Iluminada.png
    when:
      black: 0
      blue: 7
      green: 0
      red: 1
  - image: Empanada08-Iluminada.png
    when:
      black: 0
      blue: 8
      green: 0
      red: 1
  - image: Empanada09-Iluminada.png
    when:
      black: 0
      blue: 9
      green: 0
      red: 1
  - image: Empanada10-Iluminada.png
    when:
      black: 0
      blue: 10
      green: 0
      red: 1
