attire:
  active: Letras
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - Poner
    - Sacar
    - BOOM
    - RepeticionSimple
    - Asignacion
    - hayBolitas
    - nroBolitas
    - OperadorNumerico
    - OperadorDeComparacion
    - OperadorDeNegacion
    - OperadorLogico
    - OperadorSiguiente
    - OperadorPrevio
    - OperadorOpuesto
    - DefinicionDeFuncionSimpleParametrizada
    - DefinicionDeFuncionParametrizada
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - BOOM
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - AlternativaSimple
    - AlternativaCompleta
    - Asignacion
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - FuncionesPrimitivas
    - Mis funciones
    - OperadorNumerico
    - OperadorDeComparacion
    - OperadorDeNegacion
    - OperadorLogico
    - OperadorSiguiente
    - OperadorPrevio
    - OperadorOpuesto
    - DefinicionDeAsociacionDeTeclaEspecial
    - DefinicionDeAsociacionDeTeclaLetra
    - DefinicionDeAsociacionDeTeclaNúmero
    - DefinicionDeProcedimientoSimple
    - DefinicionDeProcedimientoParametrizado
    - DefinicionDeFuncionSimple
    - DefinicionDeFuncionSimpleParametrizada
    - DefinicionDeFuncionParametrizada
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: false
library:
  visible: false
name: Editor de textos simple
