attire:
  active: null
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  disabled:
    - Sacar
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - Color
    - Direccion
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: true
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: instantaneous
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Lugar para los corners
