# Site settings
title: Proyectos Gobstones Jr
header-img: img/home-bg.jpg
description: "En este sitio podrás descargar actividades para probar Gobstones Jr"
baseurl: "/proyectos-jr"
url: "http://gobstones.github.io"
github_username: "gobstones"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

# GitHub
username: gobstones
repo: proyectos-jr
branch: master

# Jekyll source / destination
source: .
destination: _site