attire:
  active: Super Lucho cuenta
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - IrAlBorde
    - BOOM
    - RepeticionSimple
    - AlternativaCompleta
    - puedeMover
    - hayBolitas
    - siguiente
    - previo
    - opuesto
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - BOOM
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - RepeticionCondicional
    - AlternativaSimple
    - AlternativaCompleta
    - Asignacion
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - FuncionesPrimitivas
    - Mis funciones
    - OperadorNumerico
    - OperadorDeComparacion
    - not
    - OperadorDeNegacion
    - OperadorLogico
    - siguiente
    - previo
    - opuesto
    - DefinicionDeProcedimientoSimple
    - DefinicionDeProcedimientoParametrizado
    - DefinicionDeFuncionSimple
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Super Lucho también cuenta las luces
