attire:
  active: Sembrando tomates
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - Poner
  visible:
    - Poner
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: medium
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: 'Bolitas, caramelos o tomates'
