name: Armamos 'El alien toca bot칩n'
attire:
  active: El alien toca bot칩n
  user_permissions:
    can_toggle_visibility: true
  visible: false
blocks:
  defaultToolbox: |
    <category name="BIBLIOTECA" gbs_custom="SEPARATOR">
    </category>
      <category name="Procedimientos primitivos">
      </category>
      <category name="Funciones primitivas">
      </category>
    <category name="MIS OPERACIONES" gbs_custom="SEPARATOR">
    </category>
      <category name="Procedimientos" gbs_custom="PROCEDURE_CALLS">
      </category>
      <category name="Funciones" gbs_custom="FUNCTION_CALLS">
      </category>
    <category name="COMANDOS" gbs_custom="SEPARATOR">
    </category>
      <category name="B치sicos">
        <block type="Poner"></block>
        <block type="Sacar"></block>
        <block type="Mover"></block>
        <block type="IrAlBorde"></block>
        <block type="VaciarTablero"></block>
        <block type="BOOM"></block>
      </category>
      <category name="Repeticiones">
        <block type="RepeticionSimple"></block>
        <block type="RepeticionCondicional"></block>
      </category>
      <category name="Alternativas">
        <block type="AlternativaSimple"></block>
        <block type="AlternativaCompleta"></block>
      </category>
      <category name="Asignaci칩n">
        <block type="Asignacion"></block>
      </category>
    <category name="EXPRESIONES" gbs_custom="SEPARATOR">
    </category>
      <category name="Valores">
        <block type="ColorSelector"></block>
        <block type="DireccionSelector"></block>
        <block type="math_number"></block>
        <block type="BoolSelector"></block>
      </category>
      <category name="Expresiones primitivas">
        <block type="hayBolitas"></block>
        <block type="puedeMover"></block>
        <block type="nroBolitas"></block>
      </category>
      <category name="Operadores">
        <block type="OperadorNumerico"></block>
        <block type="OperadorDeComparacion"></block>
        <block type="OperadorLogico"></block>
        <block type="not"></block>
        <block type="siguiente"></block>
        <block type="previo"></block>
        <block type="opuesto"></block>
      </category>
    <category name="DEFINICIONES" gbs_custom="SEPARATOR">
    </category>
      <category name="Procedimientos">
        <block type="procedures_defnoreturnnoparams"></block>
        <block type="procedures_defnoreturn"></block>
      </category>
      <category name="Funciones">
        <block type="procedures_defreturnsimple"></block>
        <block type="procedures_defreturnsimplewithparams"></block>
        <block type="procedures_defreturn"></block>
      </category>
      <category name="Eventos">
        <block type="InteractiveLetterBinding"></block>
        <block type="InteractiveNumberBinding"></block>
        <block type="InteractiveKeyBinding"></block>
      </category>
    <category name="AUXILIARES DEL DOCENTE" gbs_custom="SEPARATOR">
    </category>
      <category name="Programas">
        <block type="Program"></block>
        <block type="InteractiveProgram"></block>
      </category>
    <category name="Bloques Completar">
      <block type="ComandoCompletar"></block>
      <block type="ExpresionCompletar"></block>
      <block type="AsociacionDeTeclaCompletar"></block>
    </category>
  disabled: [ "IrAlBorde"
            , "Procedimientos primitivos"
            ]
  visible: [ "COMANDOS"    , "Poner", "Mover", "Sacar", "IrAlBorde"
                           , "Procedimientos primitivos", "Mis procedimientos"
           , "EXPRESIONES" , "Color", "Direccion"
           , "DEFINICIONES", "procedures_defnoreturnnoparams"
           ]
board:
  active: 1
  initial_board_source: selected
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_view_attire_section: true
    can_edit_board: false
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_view_size_section: false
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
