attire:
  active: Repartiendo caramelos
  user_permissions:
    can_toggle_visibility: false
  visible: true
blocks:
  disabled:
    - Poner
  visible:
    - Poner
board:
  active: 1
  initial_board_source: selected
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: false
execution_speed:
  active: medium
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Simulando repartir caramelos
source:
  visible: true
