name: Pacman
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Pastilla.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 0
  - image: Fantasma-N.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 1
  - image: Fantasma-E.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 2
  - image: Fantasma-S.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 3
  - image: Fantasma-O.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 4
  - image: Fantasma-N.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 1
  - image: Fantasma-E.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 2
  - image: Fantasma-S.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 3
  - image: Fantasma-O.png
    when:
      black: 0
      blue: 0
      green: 1
      red: 4
  - image: Pacman-N.png
    when:
      black: 1
      blue: 0
      green: 0
      red: 0
  - image: Pacman-E.png
    when:
      black: 2
      blue: 0
      green: 0
      red: 0
  - image: Pacman-S.png
    when:
      black: 3
      blue: 0
      green: 0
      red: 0
  - image: Pacman-O.png
    when:
      black: 4
      blue: 0
      green: 0
      red: 0
  - image: Pacman-N.png
    when:
      black: 1
      blue: 0
      green: 1
      red: 0
  - image: Pacman-E.png
    when:
      black: 2
      blue: 0
      green: 1
      red: 0
  - image: Pacman-S.png
    when:
      black: 3
      blue: 0
      green: 1
      red: 0
  - image: Pacman-O.png
    when:
      black: 4
      blue: 0
      green: 1
      red: 0
  - image: ParedHorizontal.png
    when:
      black: 0
      blue: 1
      green: 0
      red: 0
  - image: ParedVertical.png
    when:
      black: 0
      blue: 2
      green: 0
      red: 0
  - image: ParedEsquinaNE.png
    when:
      black: 0
      blue: 3
      green: 0
      red: 0
  - image: ParedEsquinaSE.png
    when:
      black: 0
      blue: 4
      green: 0
      red: 0
  - image: ParedEsquinaSO.png
    when:
      black: 0
      blue: 5
      green: 0
      red: 0
  - image: ParedEsquinaNO.png
    when:
      black: 0
      blue: 6
      green: 0
      red: 0
  - image: Espacio.png
    when:
      black: 0
      blue: 7
      green: 0
      red: 0
  - image: A.png
    when:
      black: 1
      blue: 7
      green: 0
      red: 0
  - image: B.png
    when:
      black: 2
      blue: 7
      green: 0
      red: 0
  - image: C.png
    when:
      black: 3
      blue: 7
      green: 0
      red: 0
  - image: D.png
    when:
      black: 4
      blue: 7
      green: 0
      red: 0
  - image: E.png
    when:
      black: 5
      blue: 7
      green: 0
      red: 0
  - image: F.png
    when:
      black: 6
      blue: 7
      green: 0
      red: 0
  - image: G.png
    when:
      black: 7
      blue: 7
      green: 0
      red: 0
  - image: H.png
    when:
      black: 8
      blue: 7
      green: 0
      red: 0
  - image: I.png
    when:
      black: 9
      blue: 7
      green: 0
      red: 0
  - image: J.png
    when:
      black: 10
      blue: 7
      green: 0
      red: 0
  - image: K.png
    when:
      black: 11
      blue: 7
      green: 0
      red: 0
  - image: L.png
    when:
      black: 12
      blue: 7
      green: 0
      red: 0
  - image: M.png
    when:
      black: 13
      blue: 7
      green: 0
      red: 0
  - image: N.png
    when:
      black: 14
      blue: 7
      green: 0
      red: 0
  - image: Ñ.png
    when:
      black: 15
      blue: 7
      green: 0
      red: 0
  - image: O.png
    when:
      black: 16
      blue: 7
      green: 0
      red: 0
  - image: P.png
    when:
      black: 17
      blue: 7
      green: 0
      red: 0
  - image: Q.png
    when:
      black: 18
      blue: 7
      green: 0
      red: 0
  - image: R.png
    when:
      black: 19
      blue: 7
      green: 0
      red: 0
  - image: S.png
    when:
      black: 20
      blue: 7
      green: 0
      red: 0
  - image: T.png
    when:
      black: 21
      blue: 7
      green: 0
      red: 0
  - image: U.png
    when:
      black: 22
      blue: 7
      green: 0
      red: 0
  - image: V.png
    when:
      black: 23
      blue: 7
      green: 0
      red: 0
  - image: W.png
    when:
      black: 24
      blue: 7
      green: 0
      red: 0
  - image: X.png
    when:
      black: 25
      blue: 7
      green: 0
      red: 0
  - image: Y.png
    when:
      black: 26
      blue: 7
      green: 0
      red: 0
  - image: Z.png
    when:
      black: 27
      blue: 7
      green: 0
      red: 0
  - image: MarkExclOpen.png
    when:
      black: 28
      blue: 7
      green: 0
      red: 0
  - image: MarkExclClose.png
    when:
      black: 29
      blue: 7
      green: 0
      red: 0
