attire:
  active: Fútbol de robots
  user_permissions:
    can_toggle_visibility: true
  visible: true
blocks:
  disabled:
    - IrAlBorde
    - BOOM
    - AlternativaSimple
    - AlternativaCompleta
    - hayBolitas
    - OperadorNumerico
    - OperadorLogico
  visible:
    - Poner
    - Mover
    - Sacar
    - IrAlBorde
    - BOOM
    - Procedimientos primitivos
    - Mis procedimientos
    - RepeticionSimple
    - RepeticionCondicional
    - AlternativaSimple
    - AlternativaCompleta
    - Color
    - Direccion
    - Numero
    - puedeMover
    - hayBolitas
    - nroBolitas
    - FuncionesPrimitivas
    - Mis funciones
    - OperadorNumerico
    - OperadorDeComparacion
    - not
    - OperadorDeNegacion
    - OperadorLogico
    - siguiente
    - previo
    - opuesto
    - procedures_defnoreturnnoparams
    - Definicion de procedimientos simples
    - procedures_defnoreturn
    - Definicion de procedimientos parametrizados
    - procedures_defreturn
    - Definicion de funciones simples
board:
  active: 1
  initial_board_source: random
  user_permissions:
    can_change_source: false
    can_edit_board: false
  visible_edition: true
execution_speed:
  active: high
  user_permissions:
    can_change_speed: true
library:
  visible: false
name: Más entrenamiento para Beto
