name: Cuadrados
rules:
  - image: Fondo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: 0
  - image: Azul.png
    when:
      black: 0
      blue: +
      green: 0
      red: 0
  - image: Negro.png
    when:
      black: +
      blue: 0
      green: 0
      red: 0
  - image: Rojo.png
    when:
      black: 0
      blue: 0
      green: 0
      red: +
  - image: Verde.png
    when:
      black: 0
      blue: 0
      green: +
      red: 0
  - image: Violeta.png
    when:
      black: 0
      blue: +
      green: 0
      red: +
